"""empty message

Revision ID: 142a1540a6dd
Revises: 3f0f0b8d5d36
Create Date: 2017-01-31 02:21:16.007636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '142a1540a6dd'
down_revision = '3f0f0b8d5d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('superusers', 'creation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable='False',
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('superusers', 'creation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
