"""empty message

Revision ID: 6ac0aff30a27
Revises: 529f1262f7dd
Create Date: 2017-01-31 08:39:40.016125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ac0aff30a27'
down_revision = '529f1262f7dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('base')
    op.alter_column('superusers', 'creation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable='False',
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'creation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable='False',
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'creation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('superusers', 'creation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('base',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='base_pkey')
    )
    # ### end Alembic commands ###
