FROM python:3.5

EXPOSE 5000
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY ./requirements.txt /usr/src/app
RUN pip install -r /usr/src/app/requirements.txt
COPY ./ /usr/src/app

CMD ["python", "/usr/src/app/run.py"]
